#define YY_parser_name_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from syntax.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "syntax.y"

	#include <stdlib.h>
	#include <stdio.h>
	int yyerror (char *yaccProvidedMessage);
	int yylex(void);

	extern int yylineno;
	extern char* yytext;
	extern FILE* yyin;


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_name_BISON 1

#ifndef YY_parser_name_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_name_COMPATIBILITY 1
 #else
  #define  YY_parser_name_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_name_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_name_LTYPE
   #define YY_parser_name_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_name_STYPE 
   #define YY_parser_name_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_name_DEBUG
   #define  YY_parser_name_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_name_USE_GOTO
  #define YY_parser_name_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_name_USE_GOTO
 #define YY_parser_name_USE_GOTO 0
#endif

#ifndef YY_parser_name_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_name_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"
#ifndef YY_USE_CLASS
# ifndef YYSTYPE
#  define YYSTYPE int
#  define YYSTYPE_IS_TRIVIAL 1
# endif
#endif

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_name_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_name_DEBUG */
#endif


#ifndef YY_parser_name_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_name_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_name_LSP_NEEDED
#ifndef YY_parser_name_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_name_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_name_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_name_STYPE
#define YY_parser_name_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_name_PARSE
#define YY_parser_name_PARSE yyparse
#endif
#ifndef YY_parser_name_LEX
#define YY_parser_name_LEX yylex
#endif
#ifndef YY_parser_name_LVAL
#define YY_parser_name_LVAL yylval
#endif
#ifndef YY_parser_name_LLOC
#define YY_parser_name_LLOC yylloc
#endif
#ifndef YY_parser_name_CHAR
#define YY_parser_name_CHAR yychar
#endif
#ifndef YY_parser_name_NERRS
#define YY_parser_name_NERRS yynerrs
#endif
#ifndef YY_parser_name_DEBUG_FLAG
#define YY_parser_name_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_name_ERROR
#define YY_parser_name_ERROR yyerror
#endif

#ifndef YY_parser_name_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_name_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_name_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_name_PARSE_PARAM
  #define YY_parser_name_PARSE_PARAM void
 #endif
#endif

#if YY_parser_name_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_name_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_name_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_name_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_name_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_name_PURE
#  endif
#endif

#ifdef YY_parser_name_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_name_DEBUG 
#  endif
#endif

#ifndef YY_parser_name_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_name_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_name_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_name_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ID	258
#define	BREAK	259
#define	CONTINUE	260
#define	AND	261
#define	OR	262
#define	NOT	263
#define	GREATEREQUAL	264
#define	LESSEQUAL	265
#define	EQUAL	266
#define	NOTEQUAL	267
#define	UMINUS	268
#define	PLUSPLUS	269
#define	MINUSMINUS	270
#define	LOCAL	271
#define	SCOPEOP	272
#define	DOUPLEDOT	273
#define	FUNCTION	274
#define	NUMBER	275
#define	STRING	276
#define	NIL	277
#define	TRUE	278
#define	FALSE	279
#define	IF	280
#define	ELSE	281
#define	WHILE	282
#define	FOR	283
#define	RETURN	284


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_name_CLASS
#define YY_parser_name_CLASS parser_name
#endif
#ifndef YY_parser_name_INHERIT
#define YY_parser_name_INHERIT
#endif
#ifndef YY_parser_name_MEMBERS
#define YY_parser_name_MEMBERS 
#endif
#ifndef YY_parser_name_LEX_BODY
#define YY_parser_name_LEX_BODY  
#endif
#ifndef YY_parser_name_ERROR_BODY
#define YY_parser_name_ERROR_BODY  
#endif
#ifndef YY_parser_name_CONSTRUCTOR_PARAM
#define YY_parser_name_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_name_CONSTRUCTOR_CODE
#define YY_parser_name_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_name_CONSTRUCTOR_INIT
#define YY_parser_name_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_name_USE_CONST_TOKEN
#define YY_parser_name_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_name_USE_CONST_TOKEN != 0
#ifndef YY_parser_name_ENUM_TOKEN
#define YY_parser_name_ENUM_TOKEN yy_parser_name_enum_token
#endif
#endif

class YY_parser_name_CLASS YY_parser_name_INHERIT
{
public: 
#if YY_parser_name_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ID;
static const int BREAK;
static const int CONTINUE;
static const int AND;
static const int OR;
static const int NOT;
static const int GREATEREQUAL;
static const int LESSEQUAL;
static const int EQUAL;
static const int NOTEQUAL;
static const int UMINUS;
static const int PLUSPLUS;
static const int MINUSMINUS;
static const int LOCAL;
static const int SCOPEOP;
static const int DOUPLEDOT;
static const int FUNCTION;
static const int NUMBER;
static const int STRING;
static const int NIL;
static const int TRUE;
static const int FALSE;
static const int IF;
static const int ELSE;
static const int WHILE;
static const int FOR;
static const int RETURN;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_name_ENUM_TOKEN { YY_parser_name_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ID=258
	,BREAK=259
	,CONTINUE=260
	,AND=261
	,OR=262
	,NOT=263
	,GREATEREQUAL=264
	,LESSEQUAL=265
	,EQUAL=266
	,NOTEQUAL=267
	,UMINUS=268
	,PLUSPLUS=269
	,MINUSMINUS=270
	,LOCAL=271
	,SCOPEOP=272
	,DOUPLEDOT=273
	,FUNCTION=274
	,NUMBER=275
	,STRING=276
	,NIL=277
	,TRUE=278
	,FALSE=279
	,IF=280
	,ELSE=281
	,WHILE=282
	,FOR=283
	,RETURN=284


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_name_PARSE (YY_parser_name_PARSE_PARAM);
 virtual void YY_parser_name_ERROR(char *msg) YY_parser_name_ERROR_BODY;
#ifdef YY_parser_name_PURE
#ifdef YY_parser_name_LSP_NEEDED
 virtual int  YY_parser_name_LEX (YY_parser_name_STYPE *YY_parser_name_LVAL,YY_parser_name_LTYPE *YY_parser_name_LLOC) YY_parser_name_LEX_BODY;
#else
 virtual int  YY_parser_name_LEX (YY_parser_name_STYPE *YY_parser_name_LVAL) YY_parser_name_LEX_BODY;
#endif
#else
 virtual int YY_parser_name_LEX() YY_parser_name_LEX_BODY;
 YY_parser_name_STYPE YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
 YY_parser_name_LTYPE YY_parser_name_LLOC;
#endif
 int   YY_parser_name_NERRS;
 int    YY_parser_name_CHAR;
#endif
#if YY_parser_name_DEBUG != 0
 int YY_parser_name_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_name_CLASS(YY_parser_name_CONSTRUCTOR_PARAM);
public:
 YY_parser_name_MEMBERS 
};
/* other declare folow */
#if YY_parser_name_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_name_CLASS::ID=258;
const int YY_parser_name_CLASS::BREAK=259;
const int YY_parser_name_CLASS::CONTINUE=260;
const int YY_parser_name_CLASS::AND=261;
const int YY_parser_name_CLASS::OR=262;
const int YY_parser_name_CLASS::NOT=263;
const int YY_parser_name_CLASS::GREATEREQUAL=264;
const int YY_parser_name_CLASS::LESSEQUAL=265;
const int YY_parser_name_CLASS::EQUAL=266;
const int YY_parser_name_CLASS::NOTEQUAL=267;
const int YY_parser_name_CLASS::UMINUS=268;
const int YY_parser_name_CLASS::PLUSPLUS=269;
const int YY_parser_name_CLASS::MINUSMINUS=270;
const int YY_parser_name_CLASS::LOCAL=271;
const int YY_parser_name_CLASS::SCOPEOP=272;
const int YY_parser_name_CLASS::DOUPLEDOT=273;
const int YY_parser_name_CLASS::FUNCTION=274;
const int YY_parser_name_CLASS::NUMBER=275;
const int YY_parser_name_CLASS::STRING=276;
const int YY_parser_name_CLASS::NIL=277;
const int YY_parser_name_CLASS::TRUE=278;
const int YY_parser_name_CLASS::FALSE=279;
const int YY_parser_name_CLASS::IF=280;
const int YY_parser_name_CLASS::ELSE=281;
const int YY_parser_name_CLASS::WHILE=282;
const int YY_parser_name_CLASS::FOR=283;
const int YY_parser_name_CLASS::RETURN=284;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_name_CLASS::token */
#endif
/*apres const  */
YY_parser_name_CLASS::YY_parser_name_CLASS(YY_parser_name_CONSTRUCTOR_PARAM) YY_parser_name_CONSTRUCTOR_INIT
{
#if YY_parser_name_DEBUG != 0
YY_parser_name_DEBUG_FLAG=0;
#endif
YY_parser_name_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		162
#define	YYFLAG		-32768
#define	YYNTBASE	48

#define YYTRANSLATE(x) ((unsigned)(x) <= 284 ? yytranslate[x] : 81)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,    37,     2,     2,    30,
    31,    35,    38,    44,    39,    34,    36,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,    46,    43,    41,
    42,    40,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
    32,     2,    33,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,    45,     2,    47,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,     5,
     6,     7,     8,     9,    10,    11,    12,    13,    14,    15,
    16,    17,    18,    19,    20,    21,    22,    23,    24,    25,
    26,    27,    28,    29
};

#if YY_parser_name_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     2,     3,     6,     9,    11,    13,    15,    17,    20,
    23,    25,    27,    29,    31,    35,    37,    39,    41,    43,
    45,    47,    49,    51,    53,    55,    57,    59,    61,    63,
    67,    70,    73,    76,    79,    82,    85,    87,    91,    93,
    95,    97,   101,   103,   105,   108,   111,   113,   117,   122,
   130,   135,   138,   145,   147,   149,   153,   159,   160,   163,
   164,   168,   170,   173,   174,   176,   178,   179,   182,   183,
   187,   193,   195,   198,   205,   206,   208,   210,   212,   214,
   216,   218,   219,   222,   223,   227,   234,   235,   238,   244,
   254,   257,   258
};

static const short yyrhs[] = {    49,
     0,     0,    50,    49,     0,    51,    43,     0,    75,     0,
    77,     0,    78,     0,    79,     0,     4,    43,     0,     5,
    43,     0,    69,     0,    70,     0,    43,     0,    54,     0,
    51,    52,    51,     0,    53,     0,    38,     0,    39,     0,
    35,     0,    36,     0,    37,     0,    40,     0,     9,     0,
    41,     0,    10,     0,    11,     0,    12,     0,     6,     0,
     7,     0,    30,    51,    31,     0,    13,    51,     0,     8,
    51,     0,    14,    56,     0,    56,    14,     0,    15,    56,
     0,    56,    15,     0,    55,     0,    56,    42,    51,     0,
    56,     0,    58,     0,    64,     0,    30,    70,    31,     0,
    72,     0,     3,     0,    16,     3,     0,    17,     3,     0,
    57,     0,    56,    34,     3,     0,    56,    32,    51,    33,
     0,    58,    34,     3,    58,    32,    51,    33,     0,    58,
    30,    62,    31,     0,    56,    59,     0,    30,    70,    31,
    30,    62,    31,     0,    60,     0,    61,     0,    30,    62,
    31,     0,    18,     3,    30,    62,    31,     0,     0,    51,
    63,     0,     0,    44,    51,    63,     0,    32,     0,    65,
    33,     0,     0,    62,     0,    66,     0,     0,    68,    67,
     0,     0,    44,    68,    67,     0,    45,    51,    46,    51,
    47,     0,    45,     0,    49,    47,     0,    19,    71,    30,
    73,    31,    69,     0,     0,     3,     0,    20,     0,    21,
     0,    22,     0,    23,     0,    24,     0,     0,     3,    74,
     0,     0,    44,     3,    74,     0,    25,    30,    51,    31,
    50,    76,     0,     0,    26,    50,     0,    27,    30,    51,
    31,    50,     0,    28,    30,    62,    43,    51,    43,    62,
    31,    50,     0,    29,    80,     0,     0,    51,     0
};

#endif

#if (YY_parser_name_DEBUG != 0) || defined(YY_parser_name_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    33,    36,    37,    40,    41,    42,    43,    44,    45,    46,
    47,    48,    49,    52,    53,    54,    58,    58,    58,    58,
    58,    58,    58,    58,    58,    58,    58,    58,    58,    60,
    61,    62,    63,    64,    65,    66,    67,    70,    72,    73,
    74,    75,    76,    79,    80,    81,    82,    85,    86,    87,
    91,    92,    93,    96,    97,   100,   102,   104,   105,   108,
   109,   112,   113,   117,   118,   119,   122,   123,   126,   127,
   130,   132,   133,   137,   139,   140,   143,   143,   143,   143,
   143,   145,   146,   149,   150,   153,   155,   156,   159,   161,
   163,   165,   166
};

static const char * const yytname[] = {   "$","error","$illegal.","ID","BREAK",
"CONTINUE","AND","OR","NOT","GREATEREQUAL","LESSEQUAL","EQUAL","NOTEQUAL","UMINUS",
"PLUSPLUS","MINUSMINUS","LOCAL","SCOPEOP","DOUPLEDOT","FUNCTION","NUMBER","STRING",
"NIL","TRUE","FALSE","IF","ELSE","WHILE","FOR","RETURN","'('","')'","'['","']'",
"'.'","'*'","'/'","'%'","'+'","'-'","'>'","'<'","'='","';'","','","'{'","':'",
"'}'","program","stmt1","stmt","expr","op","term","assignexpr","primary","lvalue",
"member","call","callsuffix","normcall","methodcall","elist","elist1","objectdef",
"objectdef1","indexed","indexed1","indexedelem","block","funcdef","funcdef1",
"const","idlist","idlist1","ifstmt","ifstmt1","whilestmt","forstmt","returnstmt",
"returnstmt1",""
};
#endif

static const short yyr1[] = {     0,
    48,    49,    49,    50,    50,    50,    50,    50,    50,    50,
    50,    50,    50,    51,    51,    51,    52,    52,    52,    52,
    52,    52,    52,    52,    52,    52,    52,    52,    52,    53,
    53,    53,    53,    53,    53,    53,    53,    54,    55,    55,
    55,    55,    55,    56,    56,    56,    56,    57,    57,    57,
    58,    58,    58,    59,    59,    60,    61,    62,    62,    63,
    63,    64,    64,    65,    65,    65,    66,    66,    67,    67,
    68,    69,    69,    70,    71,    71,    72,    72,    72,    72,
    72,    73,    73,    74,    74,    75,    76,    76,    77,    78,
    79,    80,    80
};

static const short yyr2[] = {     0,
     1,     0,     2,     2,     1,     1,     1,     1,     2,     2,
     1,     1,     1,     1,     3,     1,     1,     1,     1,     1,
     1,     1,     1,     1,     1,     1,     1,     1,     1,     3,
     2,     2,     2,     2,     2,     2,     1,     3,     1,     1,
     1,     3,     1,     1,     2,     2,     1,     3,     4,     7,
     4,     2,     6,     1,     1,     3,     5,     0,     2,     0,
     3,     1,     2,     0,     1,     1,     0,     2,     0,     3,
     5,     1,     2,     6,     0,     1,     1,     1,     1,     1,
     1,     0,     2,     0,     3,     6,     0,     2,     5,     9,
     2,     0,     1
};

static const short yydefact[] = {     2,
    44,     0,     0,    58,    58,     0,     0,     0,     0,    75,
    77,    78,    79,    80,    81,     0,     0,     0,    92,    58,
    62,    13,    72,     1,     2,    60,    16,    14,    37,    39,
    47,    40,    65,    41,     0,    66,    69,    11,    12,    43,
     5,     6,     7,     8,     9,    10,    58,    32,    31,     0,
    33,     0,    35,    45,    46,    76,     0,    58,    58,    58,
    93,    91,    60,     0,    60,    73,     3,    28,    29,    23,
    25,    26,    27,    19,    20,    21,    17,    18,    22,    24,
     4,    58,    58,    59,    34,    36,     0,    58,    58,     0,
    58,    52,    54,    55,    58,     0,    63,     0,    68,     0,
    82,    60,    60,    60,    65,    30,    42,    58,    60,    15,
     0,    65,     0,    48,    38,    65,     0,    69,     0,    84,
     0,     2,     2,    58,    58,    60,    61,    58,    56,    49,
    51,     0,     0,    70,     0,    83,     2,     0,     2,    89,
    60,    65,    71,    65,    58,    84,    11,     2,    86,    58,
    53,    57,     0,    85,    88,    65,    50,     2,    90,     0,
     0,     0
};

static const short yydefgoto[] = {   160,
    67,    25,    26,    83,    27,    28,    29,    30,    31,    32,
    92,    93,    94,    33,    84,    34,    35,    36,    99,    37,
    38,    39,    57,    40,   121,   136,    41,   149,    42,    43,
    44,    62
};

static const short yypact[] = {   254,
-32768,   -35,   -33,   313,   313,    49,    49,    11,    14,    15,
-32768,-32768,-32768,-32768,-32768,    -8,     3,     4,    23,   287,
-32768,-32768,    23,   -18,   254,   353,-32768,-32768,-32768,    85,
-32768,   -21,-32768,-32768,    17,-32768,   -14,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,   313,   545,   545,    35,
    -6,   -21,    -6,-32768,-32768,-32768,    27,   313,   313,   313,
   392,-32768,   403,    31,   340,-32768,   -18,-32768,-32768,-32768,
-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,-32768,
-32768,   313,   313,-32768,-32768,-32768,    61,   313,   313,    67,
   313,-32768,-32768,-32768,   313,    70,-32768,    29,-32768,    45,
    74,   439,   450,   545,    38,-32768,-32768,   313,   545,   545,
    48,    51,   486,-32768,    36,    54,    49,   -14,    56,    43,
    57,   254,   254,   313,   313,    95,    58,   313,-32768,-32768,
-32768,    -7,    37,-32768,    90,-32768,   254,   -18,   149,   218,
   496,    63,-32768,    64,   313,    43,    32,   254,-32768,   313,
-32768,-32768,   535,-32768,   182,    77,-32768,   254,   218,    98,
   110,-32768
};

static const short yypgoto[] = {-32768,
     0,  -107,     1,-32768,-32768,-32768,-32768,    -5,-32768,    -3,
-32768,-32768,-32768,   -53,     2,-32768,-32768,-32768,    -2,    20,
   -24,    -1,-32768,-32768,-32768,   -26,-32768,-32768,-32768,-32768,
-32768,-32768
};


#define	YYLAST		589


static const short yytable[] = {    24,
    51,    53,    52,    52,    48,    49,   105,    45,    95,    46,
    87,    87,    96,    54,   139,   140,    55,    56,    64,    61,
    63,    58,    88,    65,    89,     1,    90,    90,    66,    98,
     4,   -74,    59,    60,   112,     5,     6,     7,     8,     9,
   155,   116,    11,    12,    13,    14,    15,    65,   100,    97,
   159,     1,    20,    10,    21,   -58,   101,   -74,   102,   103,
   104,   107,   -74,   111,     8,     9,    95,    47,   145,   114,
    96,   142,   117,    47,   144,   119,   120,   128,    50,    82,
   124,   129,   109,   110,   131,   125,   135,   137,   104,   113,
   -59,   115,   146,   151,   152,   104,   156,   161,    85,    86,
    68,    69,    87,    70,    71,    72,    73,   158,   126,   162,
   127,   132,   147,   133,    88,   134,    89,   118,    90,   154,
     0,   138,   138,     0,   141,   104,    91,     0,   104,    74,
    75,    76,    77,    78,    79,    80,   138,     0,    82,     0,
     0,   143,     0,     0,     0,   153,     0,   138,   -87,     0,
   104,     1,     2,     3,     0,     0,     4,   138,     0,     0,
     0,     5,     6,     7,     8,     9,     0,    10,    11,    12,
    13,    14,    15,    16,   148,    17,    18,    19,    20,     0,
    21,   -58,     0,     0,     1,     2,     3,     0,     0,     4,
     0,    22,     0,    23,     5,     6,     7,     8,     9,     0,
    10,    11,    12,    13,    14,    15,    16,     0,    17,    18,
    19,    20,     0,    21,   -58,     0,     0,     0,     0,     0,
     1,     2,     3,     0,    22,     4,    23,     0,    -2,     0,
     5,     6,     7,     8,     9,     0,    10,    11,    12,    13,
    14,    15,    16,     0,    17,    18,    19,     0,     0,    21,
   -58,     0,     0,     0,     0,     0,     1,     2,     3,     0,
    22,     4,    23,     0,    -2,     0,     5,     6,     7,     8,
     9,     0,    10,    11,    12,    13,    14,    15,    16,     0,
    17,    18,    19,    20,     0,    21,   -58,     0,     0,     1,
     0,     0,     0,     0,     4,     0,    22,     0,    23,     5,
     6,     7,     8,     9,     0,    10,    11,    12,    13,    14,
    15,     0,     0,     0,     0,     1,    20,     0,    21,     0,
     4,     0,     0,     0,     0,     5,     6,     7,     8,     9,
     0,    47,    11,    12,    13,    14,    15,     0,     0,     0,
     0,     0,    20,     0,    21,    68,    69,     0,    70,    71,
    72,    73,     0,     0,     0,     0,     0,    47,    68,    69,
     0,    70,    71,    72,    73,     0,     0,     0,     0,     0,
     0,     0,     0,     0,    74,    75,    76,    77,    78,    79,
    80,     0,     0,    82,     0,   108,     0,    74,    75,    76,
    77,    78,    79,    80,     0,    81,    82,    68,    69,     0,
    70,    71,    72,    73,     0,     0,     0,     0,    68,    69,
     0,    70,    71,    72,    73,     0,     0,     0,     0,     0,
     0,     0,     0,     0,   -60,     0,    74,    75,    76,    77,
    78,    79,    80,   106,     0,    82,     0,    74,    75,    76,
    77,    78,    79,    80,    68,    69,    82,    70,    71,    72,
    73,     0,     0,     0,     0,    68,    69,     0,    70,    71,
    72,    73,     0,     0,     0,     0,     0,     0,     0,   122,
     0,     0,     0,    74,    75,    76,    77,    78,    79,    80,
   123,     0,    82,     0,    74,    75,    76,    77,    78,    79,
    80,    68,    69,    82,    70,    71,    72,    73,     0,     0,
     0,    68,    69,     0,    70,    71,    72,    73,     0,     0,
     0,     0,     0,     0,     0,     0,     0,     0,   130,     0,
    74,    75,    76,    77,    78,    79,    80,     0,     0,    82,
    74,    75,    76,    77,    78,    79,    80,     0,   150,    82,
    68,    69,     0,    70,    71,    72,    73,     0,     0,     0,
    68,    69,     0,    70,    71,    72,    73,     0,     0,     0,
     0,     0,     0,     0,     0,     0,     0,   157,     0,    74,
    75,    76,    77,    78,    79,    80,     0,     0,    82,    74,
    75,    76,    77,    78,    79,    80,     0,     0,    82
};

static const short yycheck[] = {     0,
     6,     7,     6,     7,     4,     5,    60,    43,    30,    43,
    18,    18,    34,     3,   122,   123,     3,     3,    20,    19,
    20,    30,    30,    23,    32,     3,    34,    34,    47,    44,
     8,     0,    30,    30,    88,    13,    14,    15,    16,    17,
   148,    95,    20,    21,    22,    23,    24,    47,    50,    33,
   158,     3,    30,    19,    32,    33,    30,    26,    58,    59,
    60,    31,    31,     3,    16,    17,    30,    45,    32,     3,
    34,   125,     3,    45,   128,    31,     3,    30,    30,    44,
    43,    31,    82,    83,    31,    30,    44,    31,    88,    89,
    33,    91,     3,    31,    31,    95,   150,     0,    14,    15,
     6,     7,    18,     9,    10,    11,    12,    31,   108,     0,
   109,   117,   137,   117,    30,   118,    32,    98,    34,   146,
    -1,   122,   123,    -1,   124,   125,    42,    -1,   128,    35,
    36,    37,    38,    39,    40,    41,   137,    -1,    44,    -1,
    -1,    47,    -1,    -1,    -1,   145,    -1,   148,     0,    -1,
   150,     3,     4,     5,    -1,    -1,     8,   158,    -1,    -1,
    -1,    13,    14,    15,    16,    17,    -1,    19,    20,    21,
    22,    23,    24,    25,    26,    27,    28,    29,    30,    -1,
    32,    33,    -1,    -1,     3,     4,     5,    -1,    -1,     8,
    -1,    43,    -1,    45,    13,    14,    15,    16,    17,    -1,
    19,    20,    21,    22,    23,    24,    25,    -1,    27,    28,
    29,    30,    -1,    32,    33,    -1,    -1,    -1,    -1,    -1,
     3,     4,     5,    -1,    43,     8,    45,    -1,    47,    -1,
    13,    14,    15,    16,    17,    -1,    19,    20,    21,    22,
    23,    24,    25,    -1,    27,    28,    29,    -1,    -1,    32,
    33,    -1,    -1,    -1,    -1,    -1,     3,     4,     5,    -1,
    43,     8,    45,    -1,    47,    -1,    13,    14,    15,    16,
    17,    -1,    19,    20,    21,    22,    23,    24,    25,    -1,
    27,    28,    29,    30,    -1,    32,    33,    -1,    -1,     3,
    -1,    -1,    -1,    -1,     8,    -1,    43,    -1,    45,    13,
    14,    15,    16,    17,    -1,    19,    20,    21,    22,    23,
    24,    -1,    -1,    -1,    -1,     3,    30,    -1,    32,    -1,
     8,    -1,    -1,    -1,    -1,    13,    14,    15,    16,    17,
    -1,    45,    20,    21,    22,    23,    24,    -1,    -1,    -1,
    -1,    -1,    30,    -1,    32,     6,     7,    -1,     9,    10,
    11,    12,    -1,    -1,    -1,    -1,    -1,    45,     6,     7,
    -1,     9,    10,    11,    12,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    35,    36,    37,    38,    39,    40,
    41,    -1,    -1,    44,    -1,    46,    -1,    35,    36,    37,
    38,    39,    40,    41,    -1,    43,    44,     6,     7,    -1,
     9,    10,    11,    12,    -1,    -1,    -1,    -1,     6,     7,
    -1,     9,    10,    11,    12,    -1,    -1,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    33,    -1,    35,    36,    37,    38,
    39,    40,    41,    31,    -1,    44,    -1,    35,    36,    37,
    38,    39,    40,    41,     6,     7,    44,     9,    10,    11,
    12,    -1,    -1,    -1,    -1,     6,     7,    -1,     9,    10,
    11,    12,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    31,
    -1,    -1,    -1,    35,    36,    37,    38,    39,    40,    41,
    31,    -1,    44,    -1,    35,    36,    37,    38,    39,    40,
    41,     6,     7,    44,     9,    10,    11,    12,    -1,    -1,
    -1,     6,     7,    -1,     9,    10,    11,    12,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    -1,    33,    -1,
    35,    36,    37,    38,    39,    40,    41,    -1,    -1,    44,
    35,    36,    37,    38,    39,    40,    41,    -1,    43,    44,
     6,     7,    -1,     9,    10,    11,    12,    -1,    -1,    -1,
     6,     7,    -1,     9,    10,    11,    12,    -1,    -1,    -1,
    -1,    -1,    -1,    -1,    -1,    -1,    -1,    33,    -1,    35,
    36,    37,    38,    39,    40,    41,    -1,    -1,    44,    35,
    36,    37,    38,    39,    40,    41,    -1,    -1,    44
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_name_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_name_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_name_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_name_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_name_CHAR = (token), YY_parser_name_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_name_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_name_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_name_PURE
/* UNPURE */
#define YYLEX           YY_parser_name_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_name_CHAR;                      /*  the lookahead symbol        */
YY_parser_name_STYPE      YY_parser_name_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_name_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_name_LSP_NEEDED
YY_parser_name_LTYPE YY_parser_name_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_name_LSP_NEEDED
#define YYLEX           YY_parser_name_LEX(&YY_parser_name_LVAL, &YY_parser_name_LLOC)
#else
#define YYLEX           YY_parser_name_LEX(&YY_parser_name_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_name_DEBUG != 0
int YY_parser_name_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_name_CLASS::
#endif
     YY_parser_name_PARSE(YY_parser_name_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_name_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_name_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_name_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_name_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_name_LSP_NEEDED
  YY_parser_name_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_name_LTYPE *yyls = yylsa;
  YY_parser_name_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_name_PURE
  int YY_parser_name_CHAR;
  YY_parser_name_STYPE YY_parser_name_LVAL;
  int YY_parser_name_NERRS;
#ifdef YY_parser_name_LSP_NEEDED
  YY_parser_name_LTYPE YY_parser_name_LLOC;
#endif
#endif

  YY_parser_name_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_name_NERRS = 0;
  YY_parser_name_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_name_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_name_LSP_NEEDED
      YY_parser_name_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_name_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_name_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_name_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_name_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_name_LSP_NEEDED
      yyls = (YY_parser_name_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_name_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_name_CHAR == YYEMPTY)
    {
#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_name_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_name_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_name_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_name_CHAR);

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_name_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_name_CHAR, YY_parser_name_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_name_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_name_CHAR != YYEOF)
    YY_parser_name_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
  *++yylsp = YY_parser_name_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_name_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_name_LLOC.first_line;
      yylsp->first_column = YY_parser_name_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_name_NERRS;

#ifdef YY_parser_name_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_name_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_name_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_name_ERROR_VERBOSE */
	YY_parser_name_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_name_CHAR == YYEOF)
	YYABORT;

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_name_CHAR, yytname[yychar1]);
#endif

      YY_parser_name_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
  *++yylsp = YY_parser_name_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 169 "syntax.y"
