#define YY_parser_name_h_included
/*#define YY_USE_CLASS 
*/
/*  A Bison++ parser, made from example.y  */

 /* with Bison++ version bison++ Version 1.21.9-1, adapted from GNU bison by coetmeur@icdc.fr
Maintained by Magnus Ekdahl <magnus@debian.org>
  */


#line 1 "/usr/share/bison++/bison.cc"
/* -*-C-*-  Note some compilers choke on comments on `#line' lines.  */
/* Skeleton output parser for bison,
   Copyright (C) 1984, 1989, 1990 Bob Corbett and Richard Stallman

   This program is free software; you can redistribute it and/or modify
   it under the terms of the GNU General Public License as published by
   the Free Software Foundation; either version 1, or (at your option)
   any later version.

   This program is distributed in the hope that it will be useful,
   but WITHOUT ANY WARRANTY; without even the implied warranty of
   MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
   GNU General Public License for more details.

   You should have received a copy of the GNU General Public License
   along with this program; if not, write to the Free Software
   Foundation, Inc., 675 Mass Ave, Cambridge, MA 02139, USA.  

   As a special exception, when this file is copied by Bison++ into a
   Bison++ output file, you may use that output file without restriction.
   This special exception was added by the Free Software Foundation
   in version 1.24 of Bison, and has been in Bison++ since 1.21.9.  

*/

/* HEADER SECTION */
#if defined( _MSDOS ) || defined(MSDOS) || defined(__MSDOS__) 
 #define __MSDOS_AND_ALIKE
#endif

#if defined(_WINDOWS) && defined(_MSC_VER)
 #define __HAVE_NO_ALLOCA
 #define __MSDOS_AND_ALIKE
#endif

#ifndef alloca
 #if defined( __GNUC__)
  #define alloca __builtin_alloca

 #elif (!defined (__STDC__) && defined (sparc)) || defined (__sparc__) || defined (__sparc)  || defined (__sgi)
  #include <alloca.h>

 #elif defined (__MSDOS_AND_ALIKE)
  #include <malloc.h>
  #ifndef __TURBOC__
   /* MS C runtime lib */
   #define alloca _alloca
  #endif

 #elif defined(_AIX)
  /* pragma must be put before any C/C++ instruction !! */
  #pragma alloca
  #include <malloc.h>

 #elif defined(__hpux)
  #ifdef __cplusplus
   extern "C" {
     void *alloca (unsigned int);
   };
  #else /* not __cplusplus */
   void *alloca ();
  #endif /* not __cplusplus */

 #endif /* not _AIX  not MSDOS, or __TURBOC__ or _AIX, not sparc.  */
#endif /* alloca not defined.  */

#ifdef c_plusplus
 #ifndef __cplusplus
  #define __cplusplus
 #endif
#endif

#ifdef __cplusplus
 #ifndef YY_USE_CLASS
/*#warning "For C++ its recomended to use bison++, otherwise classes won't be generated"*/
 #endif
#else
 #ifndef __STDC__
  #define const
 #endif
 #ifdef YY_USE_CLASS
  #error "This is a C++ header generated by bison++, please use a C++ compiler!"
 #endif
#endif

#include <stdio.h>
#define YYBISON 1  

 #line 88 "/usr/share/bison++/bison.cc"
#line 1 "example.y"
/*prologos*/
#include <stdio.h>
int yyerror (char *yaccProvidedMessage);
int yylex(void);

extern int yylineno;
extern char* yytext;
extern FILE* yyin;

%union{/*den ksero p prepei na mpei auto*/
	char *stringValue;
	int intValue;
}/*this is needed for lex actions*/


#line 88 "/usr/share/bison++/bison.cc"
/* %{ and %header{ and %union, during decl */
#define YY_parser_name_BISON 1

#ifndef YY_parser_name_COMPATIBILITY
 #ifndef YY_USE_CLASS
  #define  YY_parser_name_COMPATIBILITY 1
 #else
  #define  YY_parser_name_COMPATIBILITY 0
 #endif
#endif

#if YY_parser_name_COMPATIBILITY != 0
 /* backward compatibility */
 #ifdef YYLTYPE
  #ifndef YY_parser_name_LTYPE
   #define YY_parser_name_LTYPE YYLTYPE
  #endif
 #endif
/* Testing alternative bison solution
   /#ifdef YYSTYPE*/
#ifndef YY_parser_name_STYPE 
   #define YY_parser_name_STYPE YYSTYPE
#endif
/*#endif*/
 #ifdef YYDEBUG
  #ifndef YY_parser_name_DEBUG
   #define  YY_parser_name_DEBUG YYDEBUG
  #endif
 #endif
 
 /* use goto to be compatible */
 #ifndef YY_parser_name_USE_GOTO
  #define YY_parser_name_USE_GOTO 1
 #endif
#endif

/* use no goto to be clean in C++ */
#ifndef YY_parser_name_USE_GOTO
 #define YY_parser_name_USE_GOTO 0
#endif

#ifndef YY_parser_name_PURE

 #line 130 "/usr/share/bison++/bison.cc"

#line 130 "/usr/share/bison++/bison.cc"
/*  YY_parser_name_PURE */
#endif

/* section apres lecture def, avant lecture grammaire S2 */

 #line 134 "/usr/share/bison++/bison.cc"

#line 134 "/usr/share/bison++/bison.cc"
/* prefix */
#ifndef YY_parser_name_DEBUG

 #line 136 "/usr/share/bison++/bison.cc"

#line 136 "/usr/share/bison++/bison.cc"
/* YY_parser_name_DEBUG */
#endif


#ifndef YY_parser_name_LSP_NEEDED

 #line 141 "/usr/share/bison++/bison.cc"

#line 141 "/usr/share/bison++/bison.cc"
 /* YY_parser_name_LSP_NEEDED*/
#endif



/* DEFAULT LTYPE*/
#ifdef YY_parser_name_LSP_NEEDED
#ifndef YY_parser_name_LTYPE
#ifndef BISON_YYLTYPE_ISDECLARED
#define BISON_YYLTYPE_ISDECLARED
typedef
  struct yyltype
    {
      int timestamp;
      int first_line;
      int first_column;
      int last_line;
      int last_column;
      char *text;
   }
  yyltype;

#endif
#define YY_parser_name_LTYPE yyltype
#endif
#endif
/* DEFAULT STYPE*/
      /* We used to use `unsigned long' as YY_parser_name_STYPE on MSDOS,
	 but it seems better to be consistent.
	 Most programs should declare their own type anyway.  */

#ifndef YY_parser_name_STYPE
#define YY_parser_name_STYPE int
#endif
/* DEFAULT MISCELANEOUS */
#ifndef YY_parser_name_PARSE
#define YY_parser_name_PARSE yyparse
#endif
#ifndef YY_parser_name_LEX
#define YY_parser_name_LEX yylex
#endif
#ifndef YY_parser_name_LVAL
#define YY_parser_name_LVAL yylval
#endif
#ifndef YY_parser_name_LLOC
#define YY_parser_name_LLOC yylloc
#endif
#ifndef YY_parser_name_CHAR
#define YY_parser_name_CHAR yychar
#endif
#ifndef YY_parser_name_NERRS
#define YY_parser_name_NERRS yynerrs
#endif
#ifndef YY_parser_name_DEBUG_FLAG
#define YY_parser_name_DEBUG_FLAG yydebug
#endif
#ifndef YY_parser_name_ERROR
#define YY_parser_name_ERROR yyerror
#endif

#ifndef YY_parser_name_PARSE_PARAM
 #ifndef YY_USE_CLASS
  #ifdef YYPARSE_PARAM
   #define YY_parser_name_PARSE_PARAM void* YYPARSE_PARAM 
  #else
   #ifndef __STDC__
    #ifndef __cplusplus
     #define YY_parser_name_PARSE_PARAM
    #endif
   #endif
  #endif
 #endif
 #ifndef YY_parser_name_PARSE_PARAM
  #define YY_parser_name_PARSE_PARAM void
 #endif
#endif

#if YY_parser_name_COMPATIBILITY != 0
/* backward compatibility */
#ifdef YY_parser_name_LTYPE
#ifndef YYLTYPE
#define YYLTYPE YY_parser_name_LTYPE
#else
/* WARNING obsolete !!! user defined YYLTYPE not reported into generated header */
#endif
#endif

/* Removed due to bison compabilityproblems
/#ifndef YYSTYPE
/#define YYSTYPE YY_parser_name_STYPE
/#else*/
/* WARNING obsolete !!! user defined YYSTYPE not reported into generated header */
/*#endif*/

#ifdef YY_parser_name_PURE
#  ifndef YYPURE
#    define YYPURE YY_parser_name_PURE
#  endif
#endif

#ifdef YY_parser_name_DEBUG
#  ifndef YYDEBUG
#    define YYDEBUG YY_parser_name_DEBUG 
#  endif
#endif

#ifndef YY_parser_name_ERROR_VERBOSE
 #ifdef YYERROR_VERBOSE
  #define YY_parser_name_ERROR_VERBOSE YYERROR_VERBOSE
 #endif
#endif

#ifndef YY_parser_name_LSP_NEEDED
#  ifdef YYLSP_NEEDED
#    define YY_parser_name_LSP_NEEDED YYLSP_NEEDED
#  endif
#endif

#endif

#ifndef YY_USE_CLASS
/* TOKEN C */

 #line 263 "/usr/share/bison++/bison.cc"
#define	ID	258
#define	INTEGER	259
#define	UNIMUS	260


#line 263 "/usr/share/bison++/bison.cc"
 /* #defines tokens */
#else
/* CLASS */
#ifndef YY_parser_name_CLASS
#define YY_parser_name_CLASS parser_name
#endif
#ifndef YY_parser_name_INHERIT
#define YY_parser_name_INHERIT
#endif
#ifndef YY_parser_name_MEMBERS
#define YY_parser_name_MEMBERS 
#endif
#ifndef YY_parser_name_LEX_BODY
#define YY_parser_name_LEX_BODY  
#endif
#ifndef YY_parser_name_ERROR_BODY
#define YY_parser_name_ERROR_BODY  
#endif
#ifndef YY_parser_name_CONSTRUCTOR_PARAM
#define YY_parser_name_CONSTRUCTOR_PARAM
#endif
#ifndef YY_parser_name_CONSTRUCTOR_CODE
#define YY_parser_name_CONSTRUCTOR_CODE
#endif
#ifndef YY_parser_name_CONSTRUCTOR_INIT
#define YY_parser_name_CONSTRUCTOR_INIT
#endif
/* choose between enum and const */
#ifndef YY_parser_name_USE_CONST_TOKEN
#define YY_parser_name_USE_CONST_TOKEN 0
/* yes enum is more compatible with flex,  */
/* so by default we use it */ 
#endif
#if YY_parser_name_USE_CONST_TOKEN != 0
#ifndef YY_parser_name_ENUM_TOKEN
#define YY_parser_name_ENUM_TOKEN yy_parser_name_enum_token
#endif
#endif

class YY_parser_name_CLASS YY_parser_name_INHERIT
{
public: 
#if YY_parser_name_USE_CONST_TOKEN != 0
/* static const int token ... */

 #line 307 "/usr/share/bison++/bison.cc"
static const int ID;
static const int INTEGER;
static const int UNIMUS;


#line 307 "/usr/share/bison++/bison.cc"
 /* decl const */
#else
enum YY_parser_name_ENUM_TOKEN { YY_parser_name_NULL_TOKEN=0

 #line 310 "/usr/share/bison++/bison.cc"
	,ID=258
	,INTEGER=259
	,UNIMUS=260


#line 310 "/usr/share/bison++/bison.cc"
 /* enum token */
     }; /* end of enum declaration */
#endif
public:
 int YY_parser_name_PARSE (YY_parser_name_PARSE_PARAM);
 virtual void YY_parser_name_ERROR(char *msg) YY_parser_name_ERROR_BODY;
#ifdef YY_parser_name_PURE
#ifdef YY_parser_name_LSP_NEEDED
 virtual int  YY_parser_name_LEX (YY_parser_name_STYPE *YY_parser_name_LVAL,YY_parser_name_LTYPE *YY_parser_name_LLOC) YY_parser_name_LEX_BODY;
#else
 virtual int  YY_parser_name_LEX (YY_parser_name_STYPE *YY_parser_name_LVAL) YY_parser_name_LEX_BODY;
#endif
#else
 virtual int YY_parser_name_LEX() YY_parser_name_LEX_BODY;
 YY_parser_name_STYPE YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
 YY_parser_name_LTYPE YY_parser_name_LLOC;
#endif
 int   YY_parser_name_NERRS;
 int    YY_parser_name_CHAR;
#endif
#if YY_parser_name_DEBUG != 0
 int YY_parser_name_DEBUG_FLAG;   /*  nonzero means print parse trace     */
#endif
public:
 YY_parser_name_CLASS(YY_parser_name_CONSTRUCTOR_PARAM);
public:
 YY_parser_name_MEMBERS 
};
/* other declare folow */
#if YY_parser_name_USE_CONST_TOKEN != 0

 #line 341 "/usr/share/bison++/bison.cc"
const int YY_parser_name_CLASS::ID=258;
const int YY_parser_name_CLASS::INTEGER=259;
const int YY_parser_name_CLASS::UNIMUS=260;


#line 341 "/usr/share/bison++/bison.cc"
 /* const YY_parser_name_CLASS::token */
#endif
/*apres const  */
YY_parser_name_CLASS::YY_parser_name_CLASS(YY_parser_name_CONSTRUCTOR_PARAM) YY_parser_name_CONSTRUCTOR_INIT
{
#if YY_parser_name_DEBUG != 0
YY_parser_name_DEBUG_FLAG=0;
#endif
YY_parser_name_CONSTRUCTOR_CODE;
};
#endif

 #line 352 "/usr/share/bison++/bison.cc"


#define	YYFINAL		29
#define	YYFLAG		-32768
#define	YYNTBASE	14

#define YYTRANSLATE(x) ((unsigned)(x) <= 260 ? yytranslate[x] : 20)

static const char yytranslate[] = {     0,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,    11,
    12,     8,     6,     2,     7,     2,     9,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,    13,     2,
     5,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     2,     2,     2,     2,     2,
     2,     2,     2,     2,     2,     1,     2,     3,     4,    10
};

#if YY_parser_name_DEBUG != 0
static const short yyprhs[] = {     0,
     0,     3,     4,     6,     8,    12,    16,    20,    24,    28,
    31,    34,    37,    39,    44,    47
};

static const short yyrhs[] = {    19,
    17,     0,     0,     4,     0,     3,     0,    15,     6,    15,
     0,    15,     7,    15,     0,    15,     8,    15,     0,    15,
     9,    15,     0,    11,    15,    12,     0,     7,    15,     0,
    15,    13,     0,    17,    16,     0,    16,     0,     3,     5,
    15,    13,     0,    19,    18,     0,     0
};

#endif

#if (YY_parser_name_DEBUG != 0) || defined(YY_parser_name_ERROR_VERBOSE) 
static const short yyrline[] = { 0,
    40,    41,    44,    45,    46,    47,    48,    49,    50,    51,
    53,    55,    56,    59,    62,    63
};

static const char * const yytname[] = {   "$","error","$illegal.","ID","INTEGER",
"'='","'+'","'-'","'*'","'/'","UNIMUS","'('","')'","';'","program","expression",
"expr","expressions","assignment","assignments",""
};
#endif

static const short yyr1[] = {     0,
    14,    14,    15,    15,    15,    15,    15,    15,    15,    15,
    16,    17,    17,    18,    19,    19
};

static const short yyr2[] = {     0,
     2,     0,     1,     1,     3,     3,     3,     3,     3,     2,
     2,     2,     1,     4,     2,     0
};

static const short yydefact[] = {    16,
     0,     4,     3,     0,     0,     0,    13,     1,    15,     0,
     4,    10,     0,     0,     0,     0,     0,    11,    12,     0,
     9,     5,     6,     7,     8,    14,     0,     0,     0
};

static const short yydefgoto[] = {    27,
     6,     7,     8,     9,     1
};

static const short yypact[] = {     4,
    11,     0,-32768,    13,    13,    19,-32768,    13,-32768,    13,
-32768,-32768,    35,    13,    13,    13,    13,-32768,-32768,    27,
-32768,    -6,    -6,-32768,-32768,-32768,     7,     8,-32768
};

static const short yypgoto[] = {-32768,
    -4,     1,-32768,-32768,-32768
};


#define	YYLAST		47


static const short yytable[] = {    12,
    13,    16,    17,    -2,    10,    20,    28,    29,    19,    22,
    23,    24,    25,     2,     3,    11,     3,     4,     0,     4,
     0,     5,     0,     5,    14,    15,    16,    17,     0,     0,
     0,    18,    14,    15,    16,    17,     0,     0,     0,    26,
    14,    15,    16,    17,     0,     0,    21
};

static const short yycheck[] = {     4,
     5,     8,     9,     0,     5,    10,     0,     0,     8,    14,
    15,    16,    17,     3,     4,     3,     4,     7,    -1,     7,
    -1,    11,    -1,    11,     6,     7,     8,     9,    -1,    -1,
    -1,    13,     6,     7,     8,     9,    -1,    -1,    -1,    13,
     6,     7,     8,     9,    -1,    -1,    12
};

#line 352 "/usr/share/bison++/bison.cc"
 /* fattrs + tables */

/* parser code folow  */


/* This is the parser code that is written into each bison parser
  when the %semantic_parser declaration is not specified in the grammar.
  It was written by Richard Stallman by simplifying the hairy parser
  used when %semantic_parser is specified.  */

/* Note: dollar marks section change
   the next  is replaced by the list of actions, each action
   as one case of the switch.  */ 

#if YY_parser_name_USE_GOTO != 0
/* 
 SUPRESSION OF GOTO : on some C++ compiler (sun c++)
  the goto is strictly forbidden if any constructor/destructor
  is used in the whole function (very stupid isn't it ?)
 so goto are to be replaced with a 'while/switch/case construct'
 here are the macro to keep some apparent compatibility
*/
#define YYGOTO(lb) {yy_gotostate=lb;continue;}
#define YYBEGINGOTO  enum yy_labels yy_gotostate=yygotostart; \
                     for(;;) switch(yy_gotostate) { case yygotostart: {
#define YYLABEL(lb) } case lb: {
#define YYENDGOTO } } 
#define YYBEGINDECLARELABEL enum yy_labels {yygotostart
#define YYDECLARELABEL(lb) ,lb
#define YYENDDECLARELABEL  };
#else
/* macro to keep goto */
#define YYGOTO(lb) goto lb
#define YYBEGINGOTO 
#define YYLABEL(lb) lb:
#define YYENDGOTO
#define YYBEGINDECLARELABEL 
#define YYDECLARELABEL(lb)
#define YYENDDECLARELABEL 
#endif
/* LABEL DECLARATION */
YYBEGINDECLARELABEL
  YYDECLARELABEL(yynewstate)
  YYDECLARELABEL(yybackup)
/* YYDECLARELABEL(yyresume) */
  YYDECLARELABEL(yydefault)
  YYDECLARELABEL(yyreduce)
  YYDECLARELABEL(yyerrlab)   /* here on detecting error */
  YYDECLARELABEL(yyerrlab1)   /* here on error raised explicitly by an action */
  YYDECLARELABEL(yyerrdefault)  /* current state does not do anything special for the error token. */
  YYDECLARELABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */
  YYDECLARELABEL(yyerrhandle)  
YYENDDECLARELABEL
/* ALLOCA SIMULATION */
/* __HAVE_NO_ALLOCA */
#ifdef __HAVE_NO_ALLOCA
int __alloca_free_ptr(char *ptr,char *ref)
{if(ptr!=ref) free(ptr);
 return 0;}

#define __ALLOCA_alloca(size) malloc(size)
#define __ALLOCA_free(ptr,ref) __alloca_free_ptr((char *)ptr,(char *)ref)

#ifdef YY_parser_name_LSP_NEEDED
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		    __ALLOCA_free(yyls,yylsa)+\
		   (num)); } while(0)
#else
#define __ALLOCA_return(num) \
            do { return( __ALLOCA_free(yyss,yyssa)+\
		    __ALLOCA_free(yyvs,yyvsa)+\
		   (num)); } while(0)
#endif
#else
#define __ALLOCA_return(num) do { return(num); } while(0)
#define __ALLOCA_alloca(size) alloca(size)
#define __ALLOCA_free(ptr,ref) 
#endif

/* ENDALLOCA SIMULATION */

#define yyerrok         (yyerrstatus = 0)
#define yyclearin       (YY_parser_name_CHAR = YYEMPTY)
#define YYEMPTY         -2
#define YYEOF           0
#define YYACCEPT        __ALLOCA_return(0)
#define YYABORT         __ALLOCA_return(1)
#define YYERROR         YYGOTO(yyerrlab1)
/* Like YYERROR except do call yyerror.
   This remains here temporarily to ease the
   transition to the new meaning of YYERROR, for GCC.
   Once GCC version 2 has supplanted version 1, this can go.  */
#define YYFAIL          YYGOTO(yyerrlab)
#define YYRECOVERING()  (!!yyerrstatus)
#define YYBACKUP(token, value) \
do                                                              \
  if (YY_parser_name_CHAR == YYEMPTY && yylen == 1)                               \
    { YY_parser_name_CHAR = (token), YY_parser_name_LVAL = (value);                 \
      yychar1 = YYTRANSLATE (YY_parser_name_CHAR);                                \
      YYPOPSTACK;                                               \
      YYGOTO(yybackup);                                            \
    }                                                           \
  else                                                          \
    { YY_parser_name_ERROR ("syntax error: cannot back up"); YYERROR; }   \
while (0)

#define YYTERROR        1
#define YYERRCODE       256

#ifndef YY_parser_name_PURE
/* UNPURE */
#define YYLEX           YY_parser_name_LEX()
#ifndef YY_USE_CLASS
/* If nonreentrant, and not class , generate the variables here */
int     YY_parser_name_CHAR;                      /*  the lookahead symbol        */
YY_parser_name_STYPE      YY_parser_name_LVAL;              /*  the semantic value of the */
				/*  lookahead symbol    */
int YY_parser_name_NERRS;                 /*  number of parse errors so far */
#ifdef YY_parser_name_LSP_NEEDED
YY_parser_name_LTYPE YY_parser_name_LLOC;   /*  location data for the lookahead     */
			/*  symbol                              */
#endif
#endif


#else
/* PURE */
#ifdef YY_parser_name_LSP_NEEDED
#define YYLEX           YY_parser_name_LEX(&YY_parser_name_LVAL, &YY_parser_name_LLOC)
#else
#define YYLEX           YY_parser_name_LEX(&YY_parser_name_LVAL)
#endif
#endif
#ifndef YY_USE_CLASS
#if YY_parser_name_DEBUG != 0
int YY_parser_name_DEBUG_FLAG;                    /*  nonzero means print parse trace     */
/* Since this is uninitialized, it does not stop multiple parsers
   from coexisting.  */
#endif
#endif



/*  YYINITDEPTH indicates the initial size of the parser's stacks       */

#ifndef YYINITDEPTH
#define YYINITDEPTH 200
#endif

/*  YYMAXDEPTH is the maximum size the stacks can grow to
    (effective only if the built-in stack extension method is used).  */

#if YYMAXDEPTH == 0
#undef YYMAXDEPTH
#endif

#ifndef YYMAXDEPTH
#define YYMAXDEPTH 10000
#endif


#if __GNUC__ > 1                /* GNU C and GNU C++ define this.  */
#define __yy_bcopy(FROM,TO,COUNT)       __builtin_memcpy(TO,FROM,COUNT)
#else                           /* not GNU C or C++ */

/* This is the most reliable way to avoid incompatibilities
   in available built-in functions on various systems.  */

#ifdef __cplusplus
static void __yy_bcopy (char *from, char *to, int count)
#else
#ifdef __STDC__
static void __yy_bcopy (char *from, char *to, int count)
#else
static void __yy_bcopy (from, to, count)
     char *from;
     char *to;
     int count;
#endif
#endif
{
  register char *f = from;
  register char *t = to;
  register int i = count;

  while (i-- > 0)
    *t++ = *f++;
}
#endif


int
#ifdef YY_USE_CLASS
 YY_parser_name_CLASS::
#endif
     YY_parser_name_PARSE(YY_parser_name_PARSE_PARAM)
#ifndef __STDC__
#ifndef __cplusplus
#ifndef YY_USE_CLASS
/* parameter definition without protypes */
YY_parser_name_PARSE_PARAM_DEF
#endif
#endif
#endif
{
  register int yystate;
  register int yyn;
  register short *yyssp;
  register YY_parser_name_STYPE *yyvsp;
  int yyerrstatus;      /*  number of tokens to shift before error messages enabled */
  int yychar1=0;          /*  lookahead token as an internal (translated) token number */

  short yyssa[YYINITDEPTH];     /*  the state stack                     */
  YY_parser_name_STYPE yyvsa[YYINITDEPTH];        /*  the semantic value stack            */

  short *yyss = yyssa;          /*  refer to the stacks thru separate pointers */
  YY_parser_name_STYPE *yyvs = yyvsa;     /*  to allow yyoverflow to reallocate them elsewhere */

#ifdef YY_parser_name_LSP_NEEDED
  YY_parser_name_LTYPE yylsa[YYINITDEPTH];        /*  the location stack                  */
  YY_parser_name_LTYPE *yyls = yylsa;
  YY_parser_name_LTYPE *yylsp;

#define YYPOPSTACK   (yyvsp--, yyssp--, yylsp--)
#else
#define YYPOPSTACK   (yyvsp--, yyssp--)
#endif

  int yystacksize = YYINITDEPTH;

#ifdef YY_parser_name_PURE
  int YY_parser_name_CHAR;
  YY_parser_name_STYPE YY_parser_name_LVAL;
  int YY_parser_name_NERRS;
#ifdef YY_parser_name_LSP_NEEDED
  YY_parser_name_LTYPE YY_parser_name_LLOC;
#endif
#endif

  YY_parser_name_STYPE yyval;             /*  the variable used to return         */
				/*  semantic values from the action     */
				/*  routines                            */

  int yylen;
/* start loop, in which YYGOTO may be used. */
YYBEGINGOTO

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Starting parse\n");
#endif
  yystate = 0;
  yyerrstatus = 0;
  YY_parser_name_NERRS = 0;
  YY_parser_name_CHAR = YYEMPTY;          /* Cause a token to be read.  */

  /* Initialize stack pointers.
     Waste one element of value and location stack
     so that they stay on the same level as the state stack.
     The wasted elements are never initialized.  */

  yyssp = yyss - 1;
  yyvsp = yyvs;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp = yyls;
#endif

/* Push a new state, which is found in  yystate  .  */
/* In all cases, when you get here, the value and location stacks
   have just been pushed. so pushing a state here evens the stacks.  */
YYLABEL(yynewstate)

  *++yyssp = yystate;

  if (yyssp >= yyss + yystacksize - 1)
    {
      /* Give user a chance to reallocate the stack */
      /* Use copies of these so that the &'s don't force the real ones into memory. */
      YY_parser_name_STYPE *yyvs1 = yyvs;
      short *yyss1 = yyss;
#ifdef YY_parser_name_LSP_NEEDED
      YY_parser_name_LTYPE *yyls1 = yyls;
#endif

      /* Get the current used size of the three stacks, in elements.  */
      int size = yyssp - yyss + 1;

#ifdef yyoverflow
      /* Each stack pointer address is followed by the size of
	 the data in use in that stack, in bytes.  */
#ifdef YY_parser_name_LSP_NEEDED
      /* This used to be a conditional around just the two extra args,
	 but that might be undefined if yyoverflow is a macro.  */
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yyls1, size * sizeof (*yylsp),
		 &yystacksize);
#else
      yyoverflow("parser stack overflow",
		 &yyss1, size * sizeof (*yyssp),
		 &yyvs1, size * sizeof (*yyvsp),
		 &yystacksize);
#endif

      yyss = yyss1; yyvs = yyvs1;
#ifdef YY_parser_name_LSP_NEEDED
      yyls = yyls1;
#endif
#else /* no yyoverflow */
      /* Extend the stack our own way.  */
      if (yystacksize >= YYMAXDEPTH)
	{
	  YY_parser_name_ERROR("parser stack overflow");
	  __ALLOCA_return(2);
	}
      yystacksize *= 2;
      if (yystacksize > YYMAXDEPTH)
	yystacksize = YYMAXDEPTH;
      yyss = (short *) __ALLOCA_alloca (yystacksize * sizeof (*yyssp));
      __yy_bcopy ((char *)yyss1, (char *)yyss, size * sizeof (*yyssp));
      __ALLOCA_free(yyss1,yyssa);
      yyvs = (YY_parser_name_STYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yyvsp));
      __yy_bcopy ((char *)yyvs1, (char *)yyvs, size * sizeof (*yyvsp));
      __ALLOCA_free(yyvs1,yyvsa);
#ifdef YY_parser_name_LSP_NEEDED
      yyls = (YY_parser_name_LTYPE *) __ALLOCA_alloca (yystacksize * sizeof (*yylsp));
      __yy_bcopy ((char *)yyls1, (char *)yyls, size * sizeof (*yylsp));
      __ALLOCA_free(yyls1,yylsa);
#endif
#endif /* no yyoverflow */

      yyssp = yyss + size - 1;
      yyvsp = yyvs + size - 1;
#ifdef YY_parser_name_LSP_NEEDED
      yylsp = yyls + size - 1;
#endif

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Stack size increased to %d\n", yystacksize);
#endif

      if (yyssp >= yyss + yystacksize - 1)
	YYABORT;
    }

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Entering state %d\n", yystate);
#endif

  YYGOTO(yybackup);
YYLABEL(yybackup)

/* Do appropriate processing given the current state.  */
/* Read a lookahead token if we need one and don't already have one.  */
/* YYLABEL(yyresume) */

  /* First try to decide what to do without reference to lookahead token.  */

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yydefault);

  /* Not known => get a lookahead token if don't already have one.  */

  /* yychar is either YYEMPTY or YYEOF
     or a valid token in external form.  */

  if (YY_parser_name_CHAR == YYEMPTY)
    {
#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Reading a token: ");
#endif
      YY_parser_name_CHAR = YYLEX;
    }

  /* Convert token to internal form (in yychar1) for indexing tables with */

  if (YY_parser_name_CHAR <= 0)           /* This means end of input. */
    {
      yychar1 = 0;
      YY_parser_name_CHAR = YYEOF;                /* Don't call YYLEX any more */

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Now at end of input.\n");
#endif
    }
  else
    {
      yychar1 = YYTRANSLATE(YY_parser_name_CHAR);

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	{
	  fprintf (stderr, "Next token is %d (%s", YY_parser_name_CHAR, yytname[yychar1]);
	  /* Give the individual parser a way to print the precise meaning
	     of a token, for further debugging info.  */
#ifdef YYPRINT
	  YYPRINT (stderr, YY_parser_name_CHAR, YY_parser_name_LVAL);
#endif
	  fprintf (stderr, ")\n");
	}
#endif
    }

  yyn += yychar1;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != yychar1)
    YYGOTO(yydefault);

  yyn = yytable[yyn];

  /* yyn is what to do for this token type in this state.
     Negative => reduce, -yyn is rule number.
     Positive => shift, yyn is new state.
       New state is final state => don't bother to shift,
       just return success.
     0, or most negative number => error.  */

  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrlab);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrlab);

  if (yyn == YYFINAL)
    YYACCEPT;

  /* Shift the lookahead token.  */

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Shifting token %d (%s), ", YY_parser_name_CHAR, yytname[yychar1]);
#endif

  /* Discard the token being shifted unless it is eof.  */
  if (YY_parser_name_CHAR != YYEOF)
    YY_parser_name_CHAR = YYEMPTY;

  *++yyvsp = YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
  *++yylsp = YY_parser_name_LLOC;
#endif

  /* count tokens shifted since error; after three, turn off error status.  */
  if (yyerrstatus) yyerrstatus--;

  yystate = yyn;
  YYGOTO(yynewstate);

/* Do the default action for the current state.  */
YYLABEL(yydefault)

  yyn = yydefact[yystate];
  if (yyn == 0)
    YYGOTO(yyerrlab);

/* Do a reduction.  yyn is the number of a rule to reduce with.  */
YYLABEL(yyreduce)
  yylen = yyr2[yyn];
  if (yylen > 0)
    yyval = yyvsp[1-yylen]; /* implement default value of the action */

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      int i;

      fprintf (stderr, "Reducing via rule %d (line %d), ",
	       yyn, yyrline[yyn]);

      /* Print the symbols being reduced, and their result.  */
      for (i = yyprhs[yyn]; yyrhs[i] > 0; i++)
	fprintf (stderr, "%s ", yytname[yyrhs[i]]);
      fprintf (stderr, " -> %s\n", yytname[yyr1[yyn]]);
    }
#endif


 #line 839 "/usr/share/bison++/bison.cc"

  switch (yyn) {

case 1:
#line 40 "example.y"
{;;
    break;}
case 2:
#line 41 "example.y"
{;;
    break;}
case 3:
#line 44 "example.y"
{yyval.intValue=yyvsp[0].intValue;;
    break;}
case 4:
#line 45 "example.y"
{printf("Found ID\n");;
    break;}
case 5:
#line 46 "example.y"
{yyval.intValue=yyvsp[-2].intValue+yyvsp[0].intValue;;
    break;}
case 6:
#line 47 "example.y"
{yyval.intValue=yyvsp[-2].intValue-yyvsp[0].intValue;;
    break;}
case 7:
#line 48 "example.y"
{yyval.intValue=yyvsp[-2].intValue*yyvsp[0].intValue;;
    break;}
case 8:
#line 49 "example.y"
{yyval.intValue=yyvsp[-2].intValue/yyvsp[0].intValue;;
    break;}
case 9:
#line 50 "example.y"
{yyval.intValue=yyvsp[-1].intValue;;
    break;}
case 10:
#line 51 "example.y"
{yyval.intValue=yyvsp[0].intValue;;
    break;}
case 11:
#line 53 "example.y"
{fprintf(stdout, "Result is %d\n", yyvsp[-1].intValue);;
    break;}
case 12:
#line 55 "example.y"
{;;
    break;}
case 13:
#line 56 "example.y"
{;;
    break;}
case 14:
#line 59 "example.y"
{assign (yyvsp[-3].stringValue,yyvsp[-1].intValue);;
    break;}
case 15:
#line 62 "example.y"
{;;
    break;}
case 16:
#line 63 "example.y"
{;;
    break;}
}

#line 839 "/usr/share/bison++/bison.cc"
   /* the action file gets copied in in place of this dollarsign  */
  yyvsp -= yylen;
  yyssp -= yylen;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp -= yylen;
#endif

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

  *++yyvsp = yyval;

#ifdef YY_parser_name_LSP_NEEDED
  yylsp++;
  if (yylen == 0)
    {
      yylsp->first_line = YY_parser_name_LLOC.first_line;
      yylsp->first_column = YY_parser_name_LLOC.first_column;
      yylsp->last_line = (yylsp-1)->last_line;
      yylsp->last_column = (yylsp-1)->last_column;
      yylsp->text = 0;
    }
  else
    {
      yylsp->last_line = (yylsp+yylen-1)->last_line;
      yylsp->last_column = (yylsp+yylen-1)->last_column;
    }
#endif

  /* Now "shift" the result of the reduction.
     Determine what state that goes to,
     based on the state we popped back to
     and the rule number reduced by.  */

  yyn = yyr1[yyn];

  yystate = yypgoto[yyn - YYNTBASE] + *yyssp;
  if (yystate >= 0 && yystate <= YYLAST && yycheck[yystate] == *yyssp)
    yystate = yytable[yystate];
  else
    yystate = yydefgoto[yyn - YYNTBASE];

  YYGOTO(yynewstate);

YYLABEL(yyerrlab)   /* here on detecting error */

  if (! yyerrstatus)
    /* If not already recovering from an error, report this error.  */
    {
      ++YY_parser_name_NERRS;

#ifdef YY_parser_name_ERROR_VERBOSE
      yyn = yypact[yystate];

      if (yyn > YYFLAG && yyn < YYLAST)
	{
	  int size = 0;
	  char *msg;
	  int x, count;

	  count = 0;
	  /* Start X at -yyn if nec to avoid negative indexes in yycheck.  */
	  for (x = (yyn < 0 ? -yyn : 0);
	       x < (sizeof(yytname) / sizeof(char *)); x++)
	    if (yycheck[x + yyn] == x)
	      size += strlen(yytname[x]) + 15, count++;
	  msg = (char *) malloc(size + 15);
	  if (msg != 0)
	    {
	      strcpy(msg, "parse error");

	      if (count < 5)
		{
		  count = 0;
		  for (x = (yyn < 0 ? -yyn : 0);
		       x < (sizeof(yytname) / sizeof(char *)); x++)
		    if (yycheck[x + yyn] == x)
		      {
			strcat(msg, count == 0 ? ", expecting `" : " or `");
			strcat(msg, yytname[x]);
			strcat(msg, "'");
			count++;
		      }
		}
	      YY_parser_name_ERROR(msg);
	      free(msg);
	    }
	  else
	    YY_parser_name_ERROR ("parse error; also virtual memory exceeded");
	}
      else
#endif /* YY_parser_name_ERROR_VERBOSE */
	YY_parser_name_ERROR("parse error");
    }

  YYGOTO(yyerrlab1);
YYLABEL(yyerrlab1)   /* here on error raised explicitly by an action */

  if (yyerrstatus == 3)
    {
      /* if just tried and failed to reuse lookahead token after an error, discard it.  */

      /* return failure if at end of input */
      if (YY_parser_name_CHAR == YYEOF)
	YYABORT;

#if YY_parser_name_DEBUG != 0
      if (YY_parser_name_DEBUG_FLAG)
	fprintf(stderr, "Discarding token %d (%s).\n", YY_parser_name_CHAR, yytname[yychar1]);
#endif

      YY_parser_name_CHAR = YYEMPTY;
    }

  /* Else will try to reuse lookahead token
     after shifting the error token.  */

  yyerrstatus = 3;              /* Each real token shifted decrements this */

  YYGOTO(yyerrhandle);

YYLABEL(yyerrdefault)  /* current state does not do anything special for the error token. */

#if 0
  /* This is wrong; only states that explicitly want error tokens
     should shift them.  */
  yyn = yydefact[yystate];  /* If its default is to accept any token, ok.  Otherwise pop it.*/
  if (yyn) YYGOTO(yydefault);
#endif

YYLABEL(yyerrpop)   /* pop the current state because it cannot handle the error token */

  if (yyssp == yyss) YYABORT;
  yyvsp--;
  yystate = *--yyssp;
#ifdef YY_parser_name_LSP_NEEDED
  yylsp--;
#endif

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    {
      short *ssp1 = yyss - 1;
      fprintf (stderr, "Error: state stack now");
      while (ssp1 != yyssp)
	fprintf (stderr, " %d", *++ssp1);
      fprintf (stderr, "\n");
    }
#endif

YYLABEL(yyerrhandle)

  yyn = yypact[yystate];
  if (yyn == YYFLAG)
    YYGOTO(yyerrdefault);

  yyn += YYTERROR;
  if (yyn < 0 || yyn > YYLAST || yycheck[yyn] != YYTERROR)
    YYGOTO(yyerrdefault);

  yyn = yytable[yyn];
  if (yyn < 0)
    {
      if (yyn == YYFLAG)
	YYGOTO(yyerrpop);
      yyn = -yyn;
      YYGOTO(yyreduce);
    }
  else if (yyn == 0)
    YYGOTO(yyerrpop);

  if (yyn == YYFINAL)
    YYACCEPT;

#if YY_parser_name_DEBUG != 0
  if (YY_parser_name_DEBUG_FLAG)
    fprintf(stderr, "Shifting error token, ");
#endif

  *++yyvsp = YY_parser_name_LVAL;
#ifdef YY_parser_name_LSP_NEEDED
  *++yylsp = YY_parser_name_LLOC;
#endif

  yystate = yyn;
  YYGOTO(yynewstate);
/* end loop, in which YYGOTO may be used. */
  YYENDGOTO
}

/* END */

 #line 1038 "/usr/share/bison++/bison.cc"
#line 65 "example.y"


/*epilogos*/
int yyerror (char* yaccProvidedMessage){
	fprintf(stderr,"%s: at line %d,before token: %s\n",yaccPrividedMessage,yylineno,yytext);
	fprintf(stderr, "INPUT NOT VALID\n");
}

int main(int argc,char**argv){
	if(argc>1){
		if(!(yyin=fopen(argv[1],"r"))){
			fprintf(stderr, "Cannot read file: %s\n",argv[1] );
	
			return 1;
		}else{
			yyin=stdin;
		}
		yyparse();
		return 0;
	}

}